# Makefile for STM32H7 firmware (arm-none-eabi)
# Usage:
#   make            -> build firmware.bin (default target)
#   make flash      -> write binary to target (uses st-flash)
#   make clean      -> remove build artifacts
#   make print-vars -> show important vars
#
# You can override variables on the command line:
#   make CC=arm-none-eabi-gcc CFLAGS="-O2 ..." flash

# Toolchain
CC ?= arm-none-eabi-gcc
OBJCOPY ?= arm-none-eabi-objcopy
SIZE ?= arm-none-eabi-size

# Target filenames and locations
BUILD_DIR := build
TARGET   := $(BUILD_DIR)/firmware
ELF      := $(TARGET).elf
BIN      := $(TARGET).bin
MAP      := $(BUILD_DIR)/firmware.map

# Linker script
LDSCRIPT ?= ld/STM32H743ZITx_FLASH_DTCMRAM.ld

# Flash settings
FLASH_TOOL ?= st-flash
FLASH_ADDR ?= 0x08000000

# CPU/FPU/ABI and common flags
CPU_FLAGS := -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard
COMMON_FLAGS := -O0 -g -ffunction-sections -fdata-sections -Wall -DSTM32H753xx

CFLAGS ?= $(CPU_FLAGS) $(COMMON_FLAGS) -MMD -MP
ASFLAGS ?= -x assembler-with-cpp
LDFLAGS ?= $(CPU_FLAGS) -Wl,--gc-sections

# Include paths
INCLUDES ?= -Iinc -Isrc -Irtos/include -Iinc/hal

# Specs (if you want to enable nano or nosys)
SPECS ?=

# Sources (automatically gather .c files in common dirs)
SRC_DIRS := src src/hal rtos
C_SRCS := $(foreach d,$(SRC_DIRS),$(wildcard $(d)/*.c))
# If you have .cpp or other patterns add them above

# Assembly startup (explicit to use ASFLAGS)
ASM_SRCS := startup/startup_stm32h753xx.s

# Object files
OBJS := $(patsubst %.c,$(BUILD_DIR)/%.o,$(notdir $(C_SRCS)))
# for simplicity put all objects in $(BUILD_DIR) and use basename mapping
OBJS := $(addprefix $(BUILD_DIR)/,$(patsubst %.c,%.o,$(notdir $(C_SRCS))))
ASM_OBJS := $(patsubst %.s,$(BUILD_DIR)/%.o,$(notdir $(ASM_SRCS)))

ALL_OBJS := $(OBJS) $(ASM_OBJS)

# Default target
.PHONY: all
all: $(BIN)

# Create build dir
$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)

# C compilation rule (source files mapped by basename)
# NOTE: we use $(notdir) mapping; keep unique basenames across folders.
$(BUILD_DIR)/%.o: src/%.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(BUILD_DIR)/%.o: src/hal/%.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(BUILD_DIR)/%.o: rtos/%.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

# Assembly (startup) — allow CPP preprocessing with ASFLAGS
$(BUILD_DIR)/startup_stm32h753xx.o: startup/startup_stm32h753xx.s | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(ASFLAGS) $(INCLUDES) -c $< -o $@

# Link
$(ELF): $(ALL_OBJS) | $(BUILD_DIR)
	$(CC) $(LDFLAGS) $(ALL_OBJS) -T $(LDSCRIPT) -Wl,-Map=$(MAP) -nostartfiles $(SPECS) -o $@

# Binary
$(BIN): $(ELF)
	$(OBJCOPY) -O binary $< $@
	$(SIZE) $<

# Flash
.PHONY: flash
flash: $(BIN)
	@echo "Flashing $(BIN) to $(FLASH_ADDR) with $(FLASH_TOOL)"
	$(FLASH_TOOL) write $(BIN) $(FLASH_ADDR)

# Clean
.PHONY: clean
clean:
	@echo "Cleaning $(BUILD_DIR)"
	@rm -rf $(BUILD_DIR)
	@rm -f blinky.elf blinky.bin

# Print variables for debugging
.PHONY: print-vars
print-vars:
	@echo "CC = $(CC)"
	@echo "CFLAGS = $(CFLAGS)"
	@echo "INCLUDES = $(INCLUDES)"
	@echo "LDSCRIPT = $(LDSCRIPT)"
	@echo "OBJS ($(words $(ALL_OBJS))) = $(ALL_OBJS)"
	@echo "ELF = $(ELF)"
	@echo "BIN = $(BIN)"

# Include dependency files auto-generated by -MMD -MP
-include $(patsubst %.o,%.d,$(ALL_OBJS))

# phony targets
.PHONY: all clean flash print-vars